# Generated by Django 4.1.4 on 2023-06-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='estadocat',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, null=True, verbose_name='Estado'),
        ),
    ]
