# Generated by Django 4.1.4 on 2023-04-21 02:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_alter_servicio_id_alter_tiposervicio_id'),
        ('clientes', '0008_alter_ciudad_id_alter_cliente_id'),
        ('productos', '0007_alter_categoria_id_alter_producto_id'),
        ('usuarios', '0002_alter_usuario_options_remove_usuario_servicio_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='compra',
        ),
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'verbose_name': 'Detalle Venta', 'verbose_name_plural': 'Detalles de Ventas'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['fecha'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.RemoveField(
            model_name='venta',
            name='subTotalVenta',
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='valorTotalProducto',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total Producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='detalleVenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.detalleventa', verbose_name='Detalle Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(help_text='MM/DD/AAAA', verbose_name='Fecha Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='porcentajeIva',
            field=models.DecimalField(decimal_places=1, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Porcentaje IVA'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='totalVenta',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Venta'),
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotalVenta',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal Venta'),
        ),
    ]
