# Generated by Django 4.1.4 on 2023-07-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(help_text='MM/DD/AAAA', verbose_name='Fecha Venta'),
        ),
    ]
