<<<<<<< Updated upstream
# Generated by Django 4.1.4 on 2023-07-01 22:17
=======
# Generated by Django 4.1.5 on 2023-07-01 22:06
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
