# Generated by Django 4.1.4 on 2023-01-20 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_detalleventa_valortotalproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='valorTotalProducto',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Valor Total Producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='porcentajeIva',
            field=models.DecimalField(decimal_places=1, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Porcentaje IVA'),
        ),
    ]
