# Generated by Django 4.1.4 on 2023-01-20 03:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_detalleventa_valortotalproducto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'verbose_name': 'Detalle Venta', 'verbose_name_plural': 'Detalles de Ventas'},
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='valorTotalProducto',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total Producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subTotalVenta',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='totalVenta',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Venta'),
        ),
    ]
