# Generated by Django 4.1.4 on 2023-01-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_detalleventa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha'),
        ),
    ]
