# Generated by Django 4.1.4 on 2023-01-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_venta_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(help_text='MM/DD/AAAA', verbose_name='Fecha Venta'),
        ),
    ]
