# Generated by Django 4.1.4 on 2023-01-31 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_alter_detalleventa_id_alter_venta_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='subTotalVenta',
            new_name='subtotalVenta',
        ),
    ]
