# Generated by Django 4.1.4 on 2023-02-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_rename_subtotalventa_venta_subtotalventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='Estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
    ]
