# Generated by Django 4.1.4 on 2023-02-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_venta_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='Estado',
            new_name='estado',
        ),
    ]
