# Generated by Django 4.1.4 on 2023-07-01 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipodeservicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=200, null=True, verbose_name='Observación')),
                ('observacionFinal', models.CharField(max_length=250, null=True, verbose_name='Observación Final')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('tipoServicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipodeservicio.tiposervicio', verbose_name='Tipo de Servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['tipoServicio'],
            },
        ),
    ]
