# Generated by Django 4.1.6 on 2023-07-01 23:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipodeservicio', '0001_initial'),
        ('ciudad', '0001_initial'),
        ('tecnico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha')),
                ('observacion', models.CharField(max_length=200, null=True, verbose_name='Observación')),
                ('observacionFinal', models.CharField(max_length=250, null=True, verbose_name='Observación Final')),
                ('porcentajeIva', models.DecimalField(decimal_places=1, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Porcentaje IVA')),
                ('valorTotal', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ciudad.ciudad', verbose_name='Ciudad')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.tecnico', verbose_name='Técnico')),
                ('tipoServicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tipodeservicio.tiposervicio', verbose_name='Tipo de Servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['tipoServicio'],
            },
        ),
    ]
