# Generated by Django 4.1.4 on 2023-01-18 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0002_ciudad_alter_tecnico_numdocumento_tecnico_ciudad'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tecnico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnicos.tecnico', verbose_name='Técnico'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipoServicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.tiposervicio', verbose_name='Tipo de Servicio'),
        ),
        migrations.DeleteModel(
            name='Tecnico',
        ),
    ]
