# Generated by Django 4.1.4 on 2023-07-01 04:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0001_initial'),
        ('tipodeservicio', '0001_initial'),
        ('tecnico', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ciudad.ciudad', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='porcentajeIva',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Porcentaje IVA'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.tecnico', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='valorTotal',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipoServicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tipodeservicio.tiposervicio', verbose_name='Tipo de Servicio'),
        ),
    ]
