# Generated by Django 4.1.4 on 2023-06-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fechaEntrega',
            field=models.DateTimeField(help_text='DD/MM/AAAA', verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fechaInicio',
            field=models.DateTimeField(help_text='DD/MM/AAA', verbose_name='Fecha de Inicio'),
        ),
    ]
