# Generated by Django 4.1.4 on 2023-06-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['tipoServicio'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='fechaEntrega',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='fechaInicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tecnico',
        ),
    ]
