# Generated by Django 4.1.4 on 2023-07-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='observacion',
            field=models.CharField(default=1, max_length=300, verbose_name='Observación'),
            preserve_default=False,
        ),
    ]
