# Generated by Django 4.1.4 on 2023-07-05 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='valorTotal',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total'),
        ),
    ]
