# Generated by Django 4.1.4 on 2023-06-30 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipodeservicio', '0002_alter_tiposervicio_options'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['tipoServicio'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='nombreServicio',
        ),
        migrations.AddField(
            model_name='servicio',
            name='observacion',
            field=models.CharField(max_length=200, null=True, verbose_name='Observación'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='observacionFinal',
            field=models.CharField(max_length=250, null=True, verbose_name='Observación Final'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipoServicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipodeservicio.tiposervicio', verbose_name='Tipo de Servicio'),
        ),
    ]
