# Generated by Django 4.1.4 on 2023-07-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='observacion',
            field=models.TextField(max_length=300, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='observacionFinal',
            field=models.TextField(max_length=300, null=True, verbose_name='Observación Final'),
        ),
    ]
