# Generated by Django 4.1.4 on 2023-07-09 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicio_valorservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='valorServicio',
            field=models.PositiveBigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Servicio'),
        ),
    ]
