# Generated by Django 4.1.4 on 2023-06-30 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipodeservicio', '0001_initial'),
        ('servicios', '0002_alter_servicio_options_remove_servicio_fechaentrega_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoServicio',
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['TipoServicio'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tipoServicio',
        ),
        migrations.AddField(
            model_name='servicio',
            name='TipoServicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipodeservicio.tiposervicio', verbose_name='Tipo de Servicio'),
        ),
    ]
