# Generated by Django 4.1.4 on 2023-01-20 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_tecnico_alter_servicio_tiposervicio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['fechaInicio'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='tiposervicio',
            options={'ordering': ['nombreServicio'], 'verbose_name': 'Tipo de Servicio', 'verbose_name_plural': 'Tipos de Servicios'},
        ),
    ]
