# Generated by Django 4.1.4 on 2023-07-09 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_servicio_valorservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='observacion',
            field=models.CharField(max_length=300, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='observacionFinal',
            field=models.CharField(max_length=300, null=True, verbose_name='Observación Final'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='porcentajeIva',
            field=models.CharField(choices=[('5', 'Bienes y Servicios'), ('0', 'Exento')], default='5', max_length=2, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='valorTotal',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total'),
        ),
    ]
