# Generated by Django 4.1.4 on 2023-01-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_servicio_options_alter_tiposervicio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fechaEntrega',
            field=models.DateTimeField(verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fechaInicio',
            field=models.DateTimeField(verbose_name='Fecha de Inicio'),
        ),
    ]
