# Generated by Django 4.1.4 on 2023-06-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_delete_tiposervicio_alter_servicio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['tipoServicio'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='TipoServicio',
            new_name='tipoServicio',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='observacion',
            field=models.CharField(max_length=200, verbose_name='Observación'),
        ),
    ]
