# Generated by Django 4.1.4 on 2023-07-01 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_servicio_fecha_alter_servicio_tecnico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='porcentajeIva',
        ),
    ]
