# Generated by Django 4.1.4 on 2023-07-01 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_remove_servicio_porcentajeiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='porcentajeIva',
            field=models.DecimalField(decimal_places=1, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Porcentaje IVA'),
        ),
    ]
