# Generated by Django 4.1.4 on 2023-07-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_alter_servicio_observacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='observacionFinal',
        ),
    ]
