# Generated by Django 4.1.4 on 2023-01-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_servicio_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fechaEntrega',
            field=models.DateTimeField(help_text='MM/DD/AAAA  HH:MM:SS', verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fechaInicio',
            field=models.DateTimeField(help_text='MM/DD/AAAA  HH:MM:SS', verbose_name='Fecha de Inicio'),
        ),
    ]
