# Generated by Django 4.1.6 on 2023-06-16 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0007_alter_tecnico_id'),
        ('servicios', '0008_alter_servicio_id_alter_tiposervicio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='estado',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fechaEntrega',
            field=models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fechaInicio',
            field=models.DateField(help_text='DD/MM/AAA', verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='observacionFinal',
            field=models.CharField(max_length=250, verbose_name='Observación Final'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.tecnico', verbose_name='Técnico'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipoServicio',
            field=models.CharField(choices=[('Montaje', 'Montaje'), ('Desmontaje', 'Desmontaje'), ('Transporte', 'Transporte'), ('Otro', 'Otro')], max_length=12, null=True, verbose_name='Tipo de Servicio'),
        ),
    ]
