# Generated by Django 4.1.4 on 2023-04-21 02:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombres'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='venta',
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Teléfono'),
        ),
    ]
