# Generated by Django 4.1.4 on 2023-07-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Correo Electrónico'),
        ),
    ]
