# Generated by Django 4.1.4 on 2023-07-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='images/usuarios/perfil.jpg', upload_to='images/usuarios'),
        ),
    ]
