# Generated by Django 4.1.4 on 2023-07-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Empleado', 'Empleado')], max_length=13, verbose_name='Rol'),
        ),
    ]
