# Generated by Django 4.1.4 on 2023-07-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='media/images/usuarios/perfil.jpg', null=True, upload_to='images/usuarios'),
        ),
    ]
