# Generated by Django 4.1.4 on 2023-01-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_servicio_remove_usuario_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='\\static\\img\\perfil.jpg', upload_to='images/usuarios'),
        ),
    ]
