# Generated by Django 4.1.4 on 2023-07-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numDocumento',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Documento'),
        ),
    ]
