# Generated by Django 4.1.4 on 2023-01-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='\\static\\img\\perfil.jpg', null=True, upload_to='images/usuarios'),
        ),
    ]
