# Generated by Django 4.1.4 on 2023-07-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_numdocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Admin', 'Administrador'), ('Empl', 'Empleado')], max_length=5, verbose_name='Rol'),
        ),
    ]
