# Generated by Django 4.1.4 on 2023-02-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='default', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Nombre de Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='\\static\\img\\perfil.jpg', null=True, upload_to='images/usuarios'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.BooleanField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=3, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.BooleanField(choices=[('Admin', 'Administrador'), ('Empl', 'Empleado')], max_length=5, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoDocumento',
            field=models.BooleanField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte'), ('OT', 'Otro')], max_length=4, verbose_name='Tipo de Documento'),
        ),
    ]
