# Generated by Django 4.1.4 on 2023-02-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_usuario_tipodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.BooleanField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=3, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.BooleanField(blank=True, choices=[('Admin', 'Administrador'), ('Empl', 'Empleado')], max_length=5, null=True, verbose_name='Rol'),
        ),
    ]
