# Generated by Django 4.1.4 on 2023-01-18 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
            ],
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='numDocumento',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Documento'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnicos.ciudad', verbose_name='Ciudad'),
        ),
    ]
