# Generated by Django 4.1.4 on 2023-01-14 23:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=60, verbose_name='Nombre Categoría')),
                ('descripcion', models.TextField(max_length=300, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('precio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Precio')),
                ('especificaciones', models.TextField(max_length=300, verbose_name='Especificaciones')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('stock', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('stockMinimo', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(5)], verbose_name='Cantidad Mínima')),
                ('porcentajeIva', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Porcentaje IVA')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria', verbose_name='Categoría')),
            ],
        ),
    ]
