# Generated by Django 4.1.4 on 2023-01-21 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_categoria_options_alter_producto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stockMinimo',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5)], verbose_name='Cantidad Mínima'),
        ),
    ]
