# Generated by Django 4.1.4 on 2023-01-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_stockminimo'),
        ('productos', '0004_producto_foto_alter_producto_stockminimo'),
    ]

    operations = [
    ]
