# Generated by Django 4.1.4 on 2023-06-20 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('productos', '0007_alter_categoria_id_alter_producto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='porcentajeIva',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stockMinimo',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria', verbose_name='Categoría'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
