# Generated by Django 4.1.4 on 2023-01-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='nombreEmpresa',
        ),
    ]
