# Generated by Django 4.1.4 on 2023-01-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_nombre_cliente_nombreempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombreEmpresa',
            field=models.CharField(max_length=100, verbose_name='Nombre Empresa'),
        ),
    ]
