# Generated by Django 4.1.4 on 2023-01-18 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_nombreempresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='compra',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.ciudad', verbose_name='Ciudad'),
        ),
    ]
