# Generated by Django 4.1.4 on 2023-01-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_compra_alter_cliente_ciudad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['nombre'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombreEmpresa'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
