# Generated by Django 4.1.4 on 2023-01-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_ciudad_options_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=60, unique=True, verbose_name='Ciudad'),
        ),
    ]
