# Generated by Django 4.1.4 on 2023-01-18 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_departamento_ciudad_and_more'),
        ('usuarios', '0003_alter_usuario_foto'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='detalleCompra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.detallecompra', verbose_name='Detalle Compra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%s'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
    ]
