# Generated by Django 4.1.4 on 2023-04-21 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options_remove_usuario_servicio_and_more'),
        ('proveedores', '0008_alter_proveedor_tiempoentrega'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['fecha'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='detallecompra',
            options={'verbose_name': 'Detalle Compra', 'verbose_name_plural': 'Detalle de Compras'},
        ),
        migrations.AddField(
            model_name='compra',
            name='detalleCompra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.detallecompra', verbose_name='Detalle Compra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha Compra'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
    ]
