# Generated by Django 4.1.4 on 2023-06-30 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallecompra',
            old_name='valorTotalProducto',
            new_name='valorUnidad',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='porcentajeIva',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='subtotalCompra',
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='totalCompra',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total'),
        ),
    ]
