# Generated by Django 4.1.4 on 2023-01-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_detallecompra_compra_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['fecha'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='detallecompra',
            options={'ordering': ['cantidadMaterial'], 'verbose_name': 'Detalle Compra', 'verbose_name_plural': 'Detalle de Compras'},
        ),
    ]
