# Generated by Django 4.1.4 on 2023-06-19 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0008_alter_proveedor_tiempoentrega'),
        ('usuarios', '0003_remove_usuario_user'),
        ('compras', '0002_alter_compra_options_alter_detallecompra_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(blank=True, choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.material', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(help_text='DD/MM/AAA', verbose_name='Fecha'),
        ),
    ]
