# Generated by Django 4.1.4 on 2023-01-20 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_compra_options_alter_detallecompra_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='valorTotalMaterial',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total Material'),
        ),
    ]
