# Generated by Django 4.1.4 on 2023-01-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_detallecompra_valortotalmaterial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallecompra',
            options={'verbose_name': 'Detalle Compra', 'verbose_name_plural': 'Detalle de Compras'},
        ),
    ]
