# Generated by Django 4.1.4 on 2023-01-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_detallecompra_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha Compra'),
        ),
    ]
