# Generated by Django 4.1.4 on 2023-06-28 17:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpresa', models.CharField(max_length=100, verbose_name='Nombre Empresa')),
                ('email', models.CharField(max_length=100, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=70, verbose_name='Dirección')),
                ('modoPago', models.CharField(choices=[('EF', 'Efectivo'), ('PV', 'Pago Virtual'), ('PT', 'Pago con Tarjeta')], default='EF', max_length=3, verbose_name='Modo de Pago')),
                ('tiempoEntrega', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tiempo Entrega')),
                ('transporteIncluido', models.CharField(choices=[('sí', 'Sí'), ('No', 'No')], max_length=2, verbose_name='Transporte Incluido')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento', verbose_name='Departamento')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombreEmpresa'],
            },
        ),
    ]
