# Generated by Django 4.1.4 on 2023-07-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.BigIntegerField(unique=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.BigIntegerField(verbose_name='Teléfono'),
        ),
    ]
