# Generated by Django 4.1.4 on 2023-07-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_nit_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Correo Electrónico'),
        ),
    ]
