# Generated by Django 4.1.4 on 2023-01-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_alter_departamento_ciudad_delete_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='transporteIncluido',
            field=models.CharField(choices=[('sí', 'Sí'), ('No', 'No')], max_length=2, verbose_name='Transporte Incluido'),
        ),
    ]
