# Generated by Django 4.1.4 on 2023-02-03 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0007_alter_departamento_id_alter_material_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='tiempoEntrega',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tiempo Entrega'),
        ),
    ]
