# Generated by Django 4.1.4 on 2023-01-20 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0002_ciudad_alter_tecnico_numdocumento_tecnico_ciudad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['nombre'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='tecnico',
            options={'ordering': ['nombres'], 'verbose_name': 'Técnico', 'verbose_name_plural': 'Técnicos'},
        ),
    ]
