# Generated by Django 4.1.4 on 2023-06-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipodeservicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposervicio',
            options={'ordering': ['nombreServicio'], 'verbose_name': 'TipodeServicio', 'verbose_name_plural': 'TiposdeServicios'},
        ),
    ]
