# Generated by Django 4.1.4 on 2023-07-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipodeservicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposervicio',
            options={'ordering': ['nombreServicio'], 'verbose_name': 'Tipo de Servicio', 'verbose_name_plural': 'Tipos de Servicios'},
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='nombreServicio',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de Servicio'),
        ),
    ]
